let allMusic = [
  {
    name: "The Pectre",
    artist: "Alan Walker",
    img: "image1",
    src: "music1",
  },
  {
    name: "Anh thương em nhất mà",
    artist: "Chang",
    img: "image2",
    src: "music2",
  },
  {
    name: "Waka waka",
    artist: "Shakira",
    img: "image3",
    src: "music3",
  },
  {
    name: "Numa Numa 2",
    artist: "Dan Balan",
    img: "image4",
    src: "music4",
  },
  {
    name: "Hành Khúc Xô Viết",
    artist: "Soviet March",
    img: "image5",
    src: "music5",
  },
  {
    name: "Wavin flag",
    artist: "K'naan",
    img: "image6",
    src: "music6",
  },
  {
    name: "Mãi mãi không phải là anh",
    artist: "Thanh Bình",
    img: "image7",
    src: "music7",
  },
  {
    name: "Hymn for the weekend",
    artist: "Coldplay",
    img: "image8",
    src: "music8",
  },
  {
    name: "Tự sự",
    artist: "Orange",
    img: "image9",
    src: "music9",
  },
  {
    name: "Về bên anh",
    artist: "Jack",
    img: "image10",
    src: "music10",
  },
  {
    name: "Lạc nhau có phải muôn đời",
    artist: "ERIK",
    img: "image11",
    src: "music11",
  },
  {
    name: "Anh có cây bút nhưng không dùng vẽ hoa",
    artist: "Tình Ca",
    img: "image12",
    src: "music12",
  },
  {
    name: "Nàng thơ",
    artist: "Hoàng Dũng",
    img: "image13",
    src: "music13",
  },
  {
    name: "Đi vể nhà",
    artist: "Đen Vâu",
    img: "image14",
    src: "music14",
  },
  {
    name: "Hồi Ức",
    artist: "Phan Mạnh Quỳnh",
    img: "image15",
    src: "music15",
  },
  {
    name: "Có một nơi như thế",
    artist: "Phan Mạnh Quỳnh",
    img: "image16",
    src: "music16",
  },
  {
    name: "Nụ cười 18-20",
    artist: "Doãn Hiếu",
    img: "image17",
    src: "music17",
  },
  {
    name: "Mình cùng nhau đóng băng",
    artist: "Thùy Chi",
    img: "image18",
    src: "music18",
  },
  {
    name: "Tháng năm không trở lại",
    artist: "The wall Nutszz",
    img: "image19",
    src: "music19",
  },
  {
    name: "Phố không mùa",
    artist: "Bùi Anh Tuấn",
    img: "image20",
    src: "music20",
  },
];
